import matplotlib.pyplot as plt 
import numpy as np
y=np.arange(1,36)
plt.plot(y,'g--')
plt.plot(y+1,'r--')
plt .plot(y+2,'g--')
plt.plot(y+3,'r--')
plt.plot(y+4,'g--')
plt.plot(y+5,'r--')
plt.plot(y+6,'g--')
plt.plot(y+7,'r--')
plt .plot(y+8,'g--')
plt.plot(y+9,'r--')
plt.plot(y+10,'g--')
plt.plot(y+11,'r--')
plt.plot(y+12,'g--')
plt.plot(y+13,'r--')
plt .plot(y+14,'g--')
plt.plot(y+15,'r--')
plt.plot(y+16,'g--')
plt.plot(y+17,'r--')
plt.plot(y+18,'g--')
plt.plot(y+19,'r--')
plt .plot(y+20,'g--')
plt.plot(y+21,'r--')
plt.plot(y+22,'g--')
plt.plot(y+23,'r--')
plt.grid(True)
plt.show()